version: 2

variables:
  setup_p3: &setup_p3
    run:
      shell: /bin/bash
      name: Setup PlotCritic python3 dependencies
      command: bash .circleci/setup.sh 3
  run_func_tests: &run_func_tests
    run:
      shell: /bin/bash
      name: Functional Tests for PlotCritic
      command: bash test/func/plotcritic_test.sh
      no_output_timeout: 1h 
  macos: &macos
    macos:
      xcode: "9.4.1"
  linux: &linux
    machine: true
  install_plotcritic: &install_plotcritic
    run:
      name: Install PlotCritic
      command: python setup.py install



jobs:
  test-linux-python3:
    <<: *linux
    steps:
      - checkout
      - *setup_p3
      - *install_plotcritic
      - *run_func_tests
  #test-macos-python3:
  #  <<: *macos
  #  steps:
  #    - checkout
  #    - *setup_p3
  #    - *install_plotcritic
  #    - *run_func_tests

workflows:
  version: 2
  plotcritic-func-tests:
    jobs:
      - test-linux-python3
      - test-macos-python3
  plotcritic-nightly-func-tests:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-linux-python3
      - test-macos-python3
